# Generated by Django 5.1.1 on 2024-10-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Default comment', max_length=300),
            preserve_default=False,
        ),
    ]
